### PR TITLE
List controller implementation

### PR DESCRIPTION
**Pull request by 4rgc**
Implements the board controller, used to edit list entities.
API methods:

- `POST /list/:boardId` – add a list
    Adds a new list to a board with boardId
- `POST /list/:boardId/:listId` – update list data
    Updates list's name, description by its id
- `DELETE /list/:boardId/:listId` - delete a list
    Deletes a list by its id

### CODE REVIEW

**Comment by 4rgc** [comment]
@stalkermn Please review 🙏

**Review by ctrldrift — COMMENTED** [review]
is the list means that this is a board column?

**Comment by ctrldrift** [comment]
Please resolve conflicts

**Comment by 4rgc** [comment]
> is the list means that this is a board column?

Yep, exactly

**Comment by 4rgc** [comment]
> Please resolve conflicts

Done!

**Pull request merged**
